# Generated by Django 4.2 on 2023-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.TextField()),
                ('category', models.CharField(choices=[('AD', 'Adidas'), ('NK', 'Nike'), ('CA', 'Camisas'), ('CO', 'Conjuntos'), ('PA', 'Pantalones'), ('GO', 'Gorras')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
