# Generated by Django 4.2 on 2023-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Sin descripcion disponible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(),
        ),
    ]
