# Generated by Django 4.2.1 on 2023-05-07 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_product_description_alter_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('AH', 'Ahuachapán'), ('CA', 'Cabañas'), ('CH', 'Chalatenango'), ('CU', 'Cuscatlán'), ('LI', 'La Libertad'), ('PA', 'La Paz'), ('UN', 'La Unión'), ('MO', 'Morazán'), ('SM', 'San Miguel'), ('SS', 'San Salvador'), ('SV', 'San Vicente'), ('SA', 'Santa Ana'), ('SO', 'Sonsonate'), ('US', 'Usulután')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
