# Generated by Django 4.2 on 2023-05-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'Adidas'), ('NK', 'NIKE'), ('CA', 'Camisas'), ('CO', 'Conjuntos'), ('PA', 'Pantalones'), ('GO', 'Gorras'),], max_length=2),
        ),
    ]
