# Generated by Django 4.2 on 2023-05-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
